### ISSUE TITLE
error during the execution

### ISSUE THREAD

**Issue by Chandu-78** [yeonsumia/palmistry#3]
Traceback (most recent call last):
  File "C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\read_palm.py", line 3, in <module>
    from tools import *
  File "C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\tools.py", line 5, in <module>
    from pillow_heif import register_heif_opener
ModuleNotFoundError: No module named 'pillow_heif'

**Comment by yeonsumia** [comment]
You need to install `pillow_heif` via pip.

**Comment by Chandu-78** [comment]
We installed and it is showing requirements successfully installed.
All the requirements are successfully installed sir but getting error again and again!!
We tried everything!

**Comment by yeonsumia** [comment]
You need to check whether the package is installed at proper python path using `pip show`.

**Comment by Chandu-78** [comment]
After all tries we are getting this error again and again sir , can you please help me with this ???

PS C:\Users\purna chandu\OneDrive\Desktop\palmistry-main> python -u "c:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\read_palm.py"

usage: read_palm.py [-h] --input INPUT
read_palm.py: error: the following arguments are required: --input

**Comment by Chandu-78** [comment]
Sir can you please explain this how to execute from here ?

**Comment by yeonsumia** [comment]
The program requires --input arugment to be executed. You can tell just by looking at [this](https://github.com/yeonsumia/palmistry#run) section in README.

**Comment by Chandu-78** [comment]
PS C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code> python .\read_palm.py --input hand1.jpg
Traceback (most recent call last):
  File "C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\read_palm.py", line 56, in <module>
    main(args.input)
  File "C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\read_palm.py", line 28, in main
    remove_background(path_to_input_image, path_to_clean_image)
  File "C:\Users\purna chandu\OneDrive\Desktop\palmistry-main\code\tools.py", line 17, in remove_background
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by Chandu-78** [comment]
please send me the solution for this sir!!
